### ISSUE TITLE
Thread blocked at  MqttEndpointImpl.isConnected

### ISSUE THREAD

**Issue by zhou-hao** [vert-x3/vertx-mqtt#106]
Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 947953 ms, time limit is 10000 [io.vertx.core.VertxException: Thread blocked at io.vertx.mqtt.impl.MqttEndpointImpl.isConnected(MqttEndpointImpl.java:181) at

**Comment by vietj** [comment]
can you provide a full stack trace ?

which vertx version is it ?

**Comment by zhou-hao** [comment]
vertx version: 3.5.3

stack 1:
  Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 951955 ms, time limit is 10000 [io.vertx.core.VertxException: Thread blocked at io.vertx.mqtt.impl.MqttEndpointImpl.isConnected(MqttEndpointImpl.java:181) at com.zmcsoft.iot.interaction.vertx.mqtt.MqttClient.alive(MqttClient.java:69) at com.zmcsoft.iot.interaction.vertx.client.HashMapClientRepository.clientIsAlive(HashMapClientRepository.java:94) at com.zmcsoft.iot.interaction.vertx.client.HashMapClientRepository$$Lambda$182/1972246271.test(Unknown Source) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.LongPipeline.reduce(LongPipeline.java:438) at java.util.stream.LongPipeline.sum(LongPipeline.java:396) at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526) at com.zmcsoft.iot.interaction.vertx.client.HashMapClientRepository.lambda$init$2(HashMapClientRepository.java:178) at com.zmcsoft.iot.interaction.vertx.client.HashMapClientRepository$$Lambda$180/485542604.handle(Unknown Source) at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885) at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844) at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339) at io.vertx.core.impl.ContextImpl$$Lambda$175/118584347.run(Unknown Source) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Thread.java:745)]
stack 2:

 Thread Thread[vert.x-eventloop-thread-25,5,main] has been blocked for 975778 ms, time limit is 10000 [io.vertx.core.VertxException: Thread blocked at io.vertx.mqtt.impl.MqttEndpointImpl.isConnected(MqttEndpointImpl.java:181) at com.zmcsoft.iot.interaction.vertx.mqtt.MqttClient.close(MqttClient.java:55) at com.zmcsoft.iot.interaction.vertx.client.HashMapClientRepository.doUnregister(HashMapClientRepository.java:237) at com.zmcsoft.iot.interaction.vertx.client.HashMapClientRepository.register(HashMapClientRepository.java:159) at com.zmcsoft.iot.interaction.vertx.mqtt.VertxMqttServer.acceptConnect(VertxMqttServer.java:102) at com.zmcsoft.iot.interaction.vertx.mqtt.VertxMqttServer.doConnect(VertxMqttServer.java:76) at com.zmcsoft.iot.interaction.vertx.mqtt.VertxMqttServer$$Lambda$268/887509879.handle(Unknown Source) at io.vertx.mqtt.impl.MqttServerConnection.handleConnect(MqttServerConnection.java:282) at io.vertx.mqtt.impl.MqttServerConnection.handleMessage(MqttServerConnection.java:101) at io.vertx.mqtt.impl.MqttServerImpl.lambda$null$3(MqttServerImpl.java:94) at io.vertx.mqtt.impl.MqttServerImpl$$Lambda$309/2074107623.handle(Unknown Source) at io.vertx.core.net.impl.NetSocketImpl.handleMessageReceived(NetSocketImpl.java:351) at io.vertx.core.net.impl.NetServerImpl$2.handleMessage(NetServerImpl.java:446) at io.vertx.core.net.impl.NetServerImpl$2.handleMessage(NetServerImpl.java:443) at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146) at io.vertx.core.net.impl.VertxHandler$$Lambda$310/1971323766.run(Unknown Source) at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337) at io.vertx.core.impl.ContextImpl$$Lambda$175/118584347.run(Unknown Source) at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195) at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Thread.java:745)]

**Comment by zhou-hao** [comment]
vertx version: 3.5.3

stack 1:
```java
  Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 1214011 ms, time limit is 10000
[io.vertx.core.VertxException: Thread blocked
	at io.vertx.mqtt.impl.MqttEndpointImpl.isConnected(MqttEndpointImpl.java:181)
	at com.zmcsoft.iot.interaction.vertx.mqtt.MqttClient.alive(MqttClient.java:69)
	at com.zmcsoft.iot.interaction.vertx.client.HashMapClientRepository.clientIsAlive(HashMapClientRepository.java:94)
	at com.zmcsoft.iot.interaction.vertx.client.HashMapClientRepository$$Lambda$182/1972246271.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.LongPipeline.reduce(LongPipeline.java:438)
	at java.util.stream.LongPipeline.sum(LongPipeline.java:396)
	at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526)
	at com.zmcsoft.iot.interaction.vertx.client.HashMapClientRepository.lambda$init$2(HashMapClientRepository.java:178)
	at com.zmcsoft.iot.interaction.vertx.client.HashMapClientRepository$$Lambda$180/485542604.handle(Unknown Source)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.vertx.core.impl.ContextImpl$$Lambda$175/118584347.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)]
```
stack 2:
```java
Thread Thread[vert.x-eventloop-thread-25,5,main] has been blocked for 1237834 ms, time limit is 10000
[io.vertx.core.VertxException: Thread blocked
	at io.vertx.mqtt.impl.MqttEndpointImpl.isConnected(MqttEndpointImpl.java:181)
	at com.zmcsoft.iot.interaction.vertx.mqtt.MqttClient.close(MqttClient.java:55)
	at com.zmcsoft.iot.interaction.vertx.client.HashMapClientRepository.doUnregister(HashMapClientRepository.java:237)
	at com.zmcsoft.iot.interaction.vertx.client.HashMapClientRepository.register(HashMapClientRepository.java:159)
	at com.zmcsoft.iot.interaction.vertx.mqtt.VertxMqttServer.acceptConnect(VertxMqttServer.java:102)
	at com.zmcsoft.iot.interaction.vertx.mqtt.VertxMqttServer.doConnect(VertxMqttServer.java:76)
	at com.zmcsoft.iot.interaction.vertx.mqtt.VertxMqttServer$$Lambda$268/887509879.handle(Unknown Source)
	at io.vertx.mqtt.impl.MqttServerConnection.handleConnect(MqttServerConnection.java:282)
	at io.vertx.mqtt.impl.MqttServerConnection.handleMessage(MqttServerConnection.java:101)
	at io.vertx.mqtt.impl.MqttServerImpl.lambda$null$3(MqttServerImpl.java:94)
	at io.vertx.mqtt.impl.MqttServerImpl$$Lambda$309/2074107623.handle(Unknown Source)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessageReceived(NetSocketImpl.java:351)
	at io.vertx.core.net.impl.NetServerImpl$2.handleMessage(NetServerImpl.java:446)
	at io.vertx.core.net.impl.NetServerImpl$2.handleMessage(NetServerImpl.java:443)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.net.impl.VertxHandler$$Lambda$310/1971323766.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl$$Lambda$175/118584347.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)]
```

**Comment by konradmichael** [comment]
I have a different Deadlock, so I am adding this here. If you would like this to be a different issue just say so.
Library version is 3.6.0. I do not see any release-notes so I cannot tell if this could be fixed by using 3.6.2.

Somewhere deep in our code is a shared resource, and it is synchronized. In the TreadDump it is called "Router". The Deadlock occurred, when messages where simultaneous send and received. 

lock order within Mqtt publish handler: 
1. lock NetSocketImpl
2. lock Router

lock order within Mqtt send:
1. lock Router
2. lock NetSocketImpl

simpified Threaddump
```
"Thread-01" - Thread t@66
java.lang.Thread.State: BLOCKED
at io.vertx.core.net.impl.NetSocketImpl.writeMessage(NetSocketImpl.java:113)

    waiting to lock <19af138> (a io.vertx.core.net.impl.NetSocketImpl) owned by "vert.x-eventloop-thread-0" t@64
    at io.vertx.mqtt.impl.MqttClientImpl.write(MqttClientImpl.java:692)
    at io.vertx.mqtt.impl.MqttClientImpl.publish(MqttClientImpl.java:324)
    at io.vertx.mqtt.impl.MqttClientImpl.publish(MqttClientImpl.java:270)

    at com.company.Router.sendExternal
    at com.company.Router.receiveInternal

    locked <1e9de18> (a com.company.Router)
    at java.lang.Thread.run(Thread.java:748)

"vert.x-eventloop-thread-0" - Thread t@64
java.lang.Thread.State: BLOCKED
at com.company.Router.sendExternal

    waiting to lock <1e9de18> (a com.company.Router) owned by "Thread-01" t@66

    at com.company.Router.receiveExternal

    at io.vertx.mqtt.impl.MqttClientImpl.handlePublish(MqttClientImpl.java:916)
    at io.vertx.mqtt.impl.MqttClientImpl.handleMessage(MqttClientImpl.java:760)
    at io.vertx.mqtt.impl.MqttClientImpl.lambda$null$0(MqttClientImpl.java:192)
    at io.vertx.mqtt.impl.MqttClientImpl$$Lambda$367/171201.handle(Unknown Source)
    at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:225)
    at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:123)
    at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:369)
    locked <19af138> (a io.vertx.core.net.impl.NetSocketImpl)
    at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:386)
    at io.vertx.core.net.impl.VertxHandler$$Lambda$360/639917.handle(Unknown Source)
    at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
    at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
    at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
    at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
```

I would have expected the mqtt handler to be free of locks. But that is not the case.
How good are the chances, that we get rid of the locks inside the processHandler?

**Comment by vietj** [comment]
agreed @konradmichael

**Comment by vietj** [comment]
thanks for this precise info, is there a chance you can provide a test reproducing this ?

**Comment by vietj** [comment]
thanks

**Comment by vietj** [comment]
@konradmichael the deadlock you are observing has been fixed in this commit https://github.com/eclipse-vertx/vert.x/commit/d717e7556bc7511276ca8bc1fe49b93ced9093ca#diff-464255635b4e404921051fc7ba93471f as part of https://github.com/eclipse-vertx/vert.x/issues/2916

upgrading to 3.7.1 should fix the issue for you

for the general issue there has been deadlock fixes since it was published (in addition of the commit I reference), so I will close this issue and you should reopen a new one if you still observe it.

**Comment by eriknyk** [comment]
Hi I'm having same issue, inmy case with `kafkaConsumer.handler()`

```java
                 
   KafkaConsumer<String, String> kafkaConsumer = KafkaConsumer.create(vertx, kconfig);

    // Worker initialization
    var serviceWorker = new ServiceWorker(config, webClient);

    kafkaConsumer.handler(serviceWorker::handle);
    kafkaConsumer.subscribe(serviceWorker.getTopics(), ar0 -> {
        if (ar0.succeeded())
            logger.info("[ServiceWorker] subscribed to [" + String.join(", ", serviceWorker.getTopics()) + "] +ok");
        else
            logger.error("Could not subscribe " + ar.cause().getMessage());
    });
    kafkaConsumer.exceptionHandler(e -> {
        e.printStackTrace();
        logger.error("Error = " + e.getMessage());
    });
```
I got the error:

```
Nov 11, 2019 12:48:11 PM io.vertx.core.impl.BlockedThreadChecker WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main]=Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 7605 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.2/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base@11.0.2/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base@11.0.2/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base@11.0.2/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base@11.0.2/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base@11.0.2/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base@11.0.2/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base@11.0.2/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
	at java.base@11.0.2/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base@11.0.2/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604)
	at java.base@11.0.2/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base@11.0.2/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at app//org.springframework.ws.transport.http.HttpUrlConnection.getResponseCode(HttpUrlConnection.java:143)
	at app//org.springframework.ws.transport.http.AbstractHttpSenderConnection.hasError(AbstractHttpSenderConnection.java:53)
	at app//org.springframework.ws.client.core.WebServiceTemplate.hasError(WebServiceTemplate.java:673)
	at app//org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:607)
	at app//org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:555)
	at app//org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:390)
	at app//org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:378)
	at app//com.app.WsService.sendTransaction(WsService.java:138)
	at app//com.app.ServiceWorker.lambda$handle$0(ServiceWorker.java:83)
	at app//com.app.ServiceWorker$$Lambda$355/0x00000008003aa040.apply(Unknown Source)
```

I've tried to execute the call that taking a while becuase it is a soap call, inside a:
```java
vertx.executeBlocking(future -> { ... });
```

But the error persist.

Any help we be appreciated,
Best Regards.
